name: 'Destroy AKS Cluster'

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Azure Storage Account Key
      run: |
          ACCOUNT_KEY=$(az storage account keys list --account-name terrafomstateclaud --query '[0].value' --output tsv)
          echo "ARM_ACCESS_KEY=$ACCOUNT_KEY" >> $GITHUB_ENV
  

    - name: Terraform Init
      run: |
        terraform init -backend-config="resource_group_name=Share" \
        -backend-config="storage_account_name=terrafomstateclaud" \
        -backend-config="container_name=state" \
        -backend-config="key=terraform.tfstate"

    - name: Terraform Plan Destroy
      run: terraform plan -destroy

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
